### ISSUE TITLE
[Deployment] Any idea how I can get this up and running on my HostGator account?

### ISSUE THREAD

**Issue by wilflare** [Coursemology/coursemology.org#434]
I'm kinda lost at the Vagrant bit - hope someone can point me to the right direction

**Comment by allenwq** [comment]
@wilflare Try follow the guide of "Manually without Vagrant" ?

**Comment by wilflare** [comment]
thanks @allenwq - there's no frontend UI for me to make changes right (after deploying)?
I have to do everything through code?

**Comment by allenwq** [comment]
What do you mean by making changes ?

**Comment by wilflare** [comment]
oh like submitting new missions/quizzes/etc

**Comment by allenwq** [comment]
Yes you can, all missions /questions are created via front end UI

**Comment by wilflare** [comment]
I'm really sorry - I tried following the guide to install to my HostGator account but... my skill level is really not up to par. hope someone can advise further

**Comment by allenwq** [comment]
Can you provide more details ?

**Comment by wilflare** [comment]
I'm currently trying to follow this guide here to install it to my web server - http://support.hostgator.com/articles/specialized-help/technical/how-do-i-start-using-ruby-on-rails

but I'm getting lost as to how to get it set up on my subdomain and MySQL

**Comment by allenwq** [comment]
So you have issues when setting up mysql on your server ?  

I cannot help with the link you give me too. it's a GUI guide and I don't know what exactly the problems you are facing. normally we will do it just with the terminal.

**Comment by wilflare** [comment]
hmm would you recommend I use Heroku instead so I can get Coursemology running online?

**Comment by wilflare** [comment]
I tried Heroku and am getting this error instead
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by allenwq** [comment]
What's the output of  "heroku logs" ?

**Comment by wilflare** [comment]
2015-07-27T15:31:01.313000+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0
.0/gems/railties-3.2.14/lib/rails/commands/server.rb:70:in `start'
2015-07-27T15:31:01.312887+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0
.0/gems/rack-1.4.7/lib/rack/builder.rb:40:in `eval'
2015-07-27T15:31:01.312962+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0
.0/gems/rack-1.4.7/lib/rack/server.rb:304:in `wrapped_app'
2015-07-27T15:31:01.313019+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0
.0/gems/railties-3.2.14/lib/rails/commands.rb:55:in `block in <top (required)>'
2015-07-27T15:31:01.312981+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0
.0/gems/rack-1.4.7/lib/rack/server.rb:254:in `start'
2015-07-27T15:31:01.313057+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0
.0/gems/railties-3.2.14/lib/rails/commands.rb:50:in `<top (required)>'
2015-07-27T15:31:01.313038+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0
.0/gems/railties-3.2.14/lib/rails/commands.rb:50:in `tap'
2015-07-27T15:31:01.313076+00:00 app[web.1]:    from script/rails:6:in `require'

2015-07-27T15:31:01.313096+00:00 app[web.1]:    from script/rails:6:in `<main>'
2015-07-27T15:31:02.456157+00:00 heroku[web.1]: State changed from starting to c
rashed
2015-07-27T15:31:02.445419+00:00 heroku[web.1]: Process exited with status 1
2015-07-27T15:31:03.974313+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=wilflare-test.herokuapp.com request_id=30353c38-2
a7c-4938-8077-237e24fe6d0d fwd="103.224.118.12" dyno= connect= service= status=5
03 bytes=
2015-07-27T15:31:05.269053+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/favicon.ico" host=wilflare-test.herokuapp.com request_id
=c277ec98-e0a2-4b92-afbe-1bae50d35705 fwd="103.224.118.12" dyno= connect= servic
e= status=503 bytes=
2015-07-27T15:33:25.840559+00:00 heroku[api]: Scale to web=1 by wilflare@gmail.c
om
2015-07-27T15:34:57.344958+00:00 heroku[api]: Scale to web=1, worker=1 by wilfla
re@gmail.com
2015-07-27T15:34:57.333965+00:00 heroku[api]: Scale to web=1, worker=1 by wilfla
re@gmail.com
2015-07-27T15:35:07.298369+00:00 heroku[worker.1]: Starting process with command
 `bundle exec rake jobs:work`
2015-07-27T15:35:08.178137+00:00 heroku[worker.1]: State changed from starting t
o up
2015-07-27T15:35:14.905624+00:00 app[worker.1]: DEPRECATION WARNING: You have Ra
ils 2.3-style plugins in vendor/plugins! Support for these plugins will be remov
ed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in
to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the relea
se notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc
2-has-been-released. (called from <top (required)> at /app/Rakefile:7)
2015-07-27T15:35:14.905845+00:00 app[worker.1]: DEPRECATION WARNING: You have Ra
ils 2.3-style plugins in vendor/plugins! Support for these plugins will be remov
ed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in
to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the relea
se notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc
2-has-been-released. (called from <top (required)> at /app/Rakefile:7)
2015-07-27T15:35:15.884775+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/bundler-1.9.7/lib/bundler/rubygems_integration.rb:263:in `block in replace_ge
m'
2015-07-27T15:35:15.884371+00:00 app[worker.1]: rake aborted!
2015-07-27T15:35:15.884441+00:00 app[worker.1]: LoadError: Please install the po
stgresql adapter: `gem install activerecord-postgresql-adapter` (pg is not part
of the bundle. Add it to Gemfile.)
2015-07-27T15:35:15.884779+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
2015-07-27T15:35:15.884781+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `block in requ
ire'
2015-07-27T15:35:15.884777+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.
rb:7:in `<top (required)>'
2015-07-27T15:35:15.884782+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependen
cy'
2015-07-27T15:35:15.884787+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection
_specification.rb:41:in `resolve_string_connection'
2015-07-27T15:35:15.884784+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
2015-07-27T15:35:15.884790+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection
_specification.rb:130:in `establish_connection'
2015-07-27T15:35:15.884793+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/lazy_load_hooks.rb:36:in `instance_ev
al'
2015-07-27T15:35:15.884786+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection
_specification.rb:50:in `resolve_hash_connection'
2015-07-27T15:35:15.884792+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/railtie.rb:88:in `block (2 levels) in <
class:Railtie>'
2015-07-27T15:35:15.884796+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/lazy_load_hooks.rb:26:in `block in on
_load'
2015-07-27T15:35:15.884797+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/lazy_load_hooks.rb:25:in `each'
2015-07-27T15:35:15.884799+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
2015-07-27T15:35:15.884800+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/railtie.rb:80:in `block in <class:Railt
ie>'
2015-07-27T15:35:15.884803+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/initializable.rb:30:in `run'
2015-07-27T15:35:15.884801+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/initializable.rb:30:in `instance_exec'
2015-07-27T15:35:15.884806+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/initializable.rb:54:in `each'
2015-07-27T15:35:15.884795+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/lazy_load_hooks.rb:36:in `execute_hoo
k'
2015-07-27T15:35:15.884789+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection
_specification.rb:27:in `spec'
2015-07-27T15:35:15.884805+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/initializable.rb:55:in `block in run_initializers'
2015-07-27T15:35:15.884808+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/application.rb:136:in `initialize!'
2015-07-27T15:35:15.884807+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/initializable.rb:54:in `run_initializers'
2015-07-27T15:35:15.884812+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
2015-07-27T15:35:15.884809+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
2015-07-27T15:35:15.884811+00:00 app[worker.1]: /app/config/environment.rb:5:in
`<top (required)>'
2015-07-27T15:35:15.884831+00:00 app[worker.1]: (See full trace by running task
with --trace)
2015-07-27T15:35:15.884823+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/application.rb:305:in `block (2 levels) in initiali
ze_tasks'
2015-07-27T15:35:15.884818+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `block in requ
ire'
2015-07-27T15:35:15.884819+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependen
cy'
2015-07-27T15:35:15.884820+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
2015-07-27T15:35:15.884822+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/application.rb:103:in `require_environment!'
2015-07-27T15:35:15.884828+00:00 app[worker.1]: Tasks: TOP => jobs:work => jobs:
environment_options => environment
2015-07-27T15:35:16.823351+00:00 heroku[worker.1]: State changed from crashed to
 starting
2015-07-27T15:35:16.804788+00:00 heroku[worker.1]: Process exited with status 1
2015-07-27T15:35:16.821422+00:00 heroku[worker.1]: State changed from up to cras
hed
2015-07-27T15:35:20.367006+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=wilflare-test.herokuapp.com request_id=1ee82540-d
71d-4726-8f58-cfef8cda743d fwd="103.224.118.12" dyno= connect= service= status=5
03 bytes=
2015-07-27T15:35:21.432206+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/favicon.ico" host=wilflare-test.herokuapp.com request_id
=080e74c1-be5a-4725-8f89-669f2102a461 fwd="103.224.118.12" dyno= connect= servic
e= status=503 bytes=
2015-07-27T15:35:25.743523+00:00 heroku[worker.1]: Starting process with command
 `bundle exec rake jobs:work`
2015-07-27T15:35:26.627600+00:00 heroku[worker.1]: State changed from starting t
o up
2015-07-27T15:35:35.447839+00:00 app[worker.1]: DEPRECATION WARNING: You have Ra
ils 2.3-style plugins in vendor/plugins! Support for these plugins will be remov
ed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in
to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the relea
se notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc
2-has-been-released. (called from <top (required)> at /app/Rakefile:7)
2015-07-27T15:35:35.448064+00:00 app[worker.1]: DEPRECATION WARNING: You have Ra
ils 2.3-style plugins in vendor/plugins! Support for these plugins will be remov
ed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in
to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the relea
se notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc
2-has-been-released. (called from <top (required)> at /app/Rakefile:7)
2015-07-27T15:35:36.397214+00:00 app[worker.1]: rake aborted!
2015-07-27T15:35:36.397683+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
2015-07-27T15:35:36.397368+00:00 app[worker.1]: LoadError: Please install the po
stgresql adapter: `gem install activerecord-postgresql-adapter` (pg is not part
of the bundle. Add it to Gemfile.)
2015-07-27T15:35:36.397684+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `block in requ
ire'
2015-07-27T15:35:36.397678+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/bundler-1.9.7/lib/bundler/rubygems_integration.rb:263:in `block in replace_ge
m'
2015-07-27T15:35:36.397693+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection
_specification.rb:41:in `resolve_string_connection'
2015-07-27T15:35:36.397686+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependen
cy'
2015-07-27T15:35:36.397689+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
2015-07-27T15:35:36.397700+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/lazy_load_hooks.rb:36:in `instance_ev
al'
2015-07-27T15:35:36.397692+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection
_specification.rb:50:in `resolve_hash_connection'
2015-07-27T15:35:36.397695+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection
_specification.rb:27:in `spec'
2015-07-27T15:35:36.397698+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/railtie.rb:88:in `block (2 levels) in <
class:Railtie>'
2015-07-27T15:35:36.397704+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/lazy_load_hooks.rb:25:in `each'
2015-07-27T15:35:36.397681+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/connection_adapters/postgresql_adapter.
rb:7:in `<top (required)>'
2015-07-27T15:35:36.397697+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/connection_adapters/abstract/connection
_specification.rb:130:in `establish_connection'
2015-07-27T15:35:36.397711+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/initializable.rb:55:in `block in run_initializers'
2015-07-27T15:35:36.397706+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activerecord-3.2.14/lib/active_record/railtie.rb:80:in `block in <class:Railt
ie>'
2015-07-27T15:35:36.397709+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/initializable.rb:30:in `run'
2015-07-27T15:35:36.397705+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
2015-07-27T15:35:36.397712+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/initializable.rb:54:in `each'
2015-07-27T15:35:36.397714+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/initializable.rb:54:in `run_initializers'
2015-07-27T15:35:36.397728+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependen
cy'
2015-07-27T15:35:36.397701+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/lazy_load_hooks.rb:36:in `execute_hoo
k'
2015-07-27T15:35:36.397702+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/lazy_load_hooks.rb:26:in `block in on
_load'
2015-07-27T15:35:36.397708+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/initializable.rb:30:in `instance_exec'
2015-07-27T15:35:36.397719+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
2015-07-27T15:35:36.397861+00:00 app[worker.1]: (See full trace by running task
with --trace)
2015-07-27T15:35:36.397717+00:00 app[worker.1]: /app/config/environment.rb:5:in
`<top (required)>'
2015-07-27T15:35:36.397729+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
2015-07-27T15:35:36.397716+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
2015-07-27T15:35:36.397715+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/application.rb:136:in `initialize!'
2015-07-27T15:35:36.397720+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `block in requ
ire'
2015-07-27T15:35:36.397730+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/application.rb:103:in `require_environment!'
2015-07-27T15:35:36.397818+00:00 app[worker.1]: Tasks: TOP => jobs:work => jobs:
environment_options => environment
2015-07-27T15:35:36.397732+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/ge
ms/railties-3.2.14/lib/rails/application.rb:305:in `block (2 levels) in initiali
ze_tasks'
2015-07-27T15:35:37.403457+00:00 heroku[worker.1]: Process exited with status 1
2015-07-27T15:35:37.408830+00:00 heroku[worker.1]: State changed from up to cras
hed

**Comment by allenwq** [comment]
"Please install the po stgresql adapter:gem install activerecord-postgresql-adapter(pg is not part of the bundle. Add it to Gemfile.)"

I realised that heroku natively uses postgres while coursemology uses mysql, that's why you get the error.

**Comment by wilflare** [comment]
oh... guess I can't use heroku for this then?
was hoping to run this online rather than a local machine :/

**Comment by allenwq** [comment]
You try to change coursemology's  db to postgres ? but I'm not sure if it will work.

**Comment by wilflare** [comment]
haha that would be beyond my ability unfortunately
I supposed coursemology2 would result in the same issue right?

**Comment by allenwq** [comment]
Coursemology2 uses postgres :)

**Comment by wilflare** [comment]
ah that's great news but I'm having another set of problems with coursemology2 - lemme get the log

**Comment by wilflare** [comment]
something to do with the bundler version :/
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.0.0
###### WARNING:
       Removing `Gemfile.lock` because it was generated on Windows.
       Bundler will do a full resolve so native gems are handled properly.
       This may result in unexpected gem versions being used in your app.
       In rare occasions Bundler may not be able to resolve your dependencies at all.
       https://devcenter.heroku.com/articles/bundler-windows-gemfile
-----> Installing dependencies using 1.9.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4
       Fetching git://github.com/doabit/bootstrap-sass-extras.git
       Fetching git://github.com/thedarkone/rails-dev-boost.git
       Fetching git://github.com/lowjoel/themes_on_rails.git
       Fetching git://github.com/carrierwaveuploader/carrierwave.git
       Fetching gem metadata from https://rails-assets.org/...
       Fetching version metadata from https://rails-assets.org/..
       Fetching gem metadata from https://rubygems.org/.......
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Resolving dependencies...
       Bundler could not find compatible versions for gem "bundler":
       In Gemfile:
       bundler (>= 1.10.3) ruby
       Current Bundler version:
       bundler (1.9.7)
       This Gemfile requires a different version of Bundler.
       Perhaps you need to update Bundler by running `gem install bundler`?
       Could not find gem 'bundler (>= 1.10.3) ruby in any of the sources
       Bundler Output: Fetching git://github.com/doabit/bootstrap-sass-extras.git
       Fetching git://github.com/thedarkone/rails-dev-boost.git
       Fetching git://github.com/lowjoel/themes_on_rails.git
       Fetching git://github.com/carrierwaveuploader/carrierwave.git
       Fetching gem metadata from https://rails-assets.org/...
       Fetching version metadata from https://rails-assets.org/..
       Fetching gem metadata from https://rubygems.org/.......
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Resolving dependencies...
       Bundler could not find compatible versions for gem "bundler":
       In Gemfile:
       bundler (>= 1.10.3) ruby
       
       Current Bundler version:
       bundler (1.9.7)
       This Gemfile requires a different version of Bundler.
       Perhaps you need to update Bundler by running `gem install bundler`?
       Could not find gem 'bundler (>= 1.10.3) ruby in any of the sources
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app

**Comment by allenwq** [comment]
You need to `gem update bundler` first, then make sure you are using ruby 2.1 +

**Comment by wilflare** [comment]
I followed the instructions here... - https://devcenter.heroku.com/articles/getting-started-with-jruby#introduction 

what else should I do?

**Comment by allenwq** [comment]
You should follow this guide to setup coursemology: https://devcenter.heroku.com/articles/getting-started-with-rails3

And this guide for coursemology2, which is rails 4: https://devcenter.heroku.com/articles/getting-started-with-rails4

**Comment by wilflare** [comment]
think I really need to sit down and read through the whole chunk.
thought I could just deploy it and see how it works - and whether it'll fit what I hope to achieve...

(how do the groups here - http://coursemology.org/courses get all their content online?)

**Comment by allenwq** [comment]
@wilflare  Have you created any courses ?

**Comment by wilflare** [comment]
nope I have not :(

**Comment by allenwq** [comment]
I need more details otherwise cannot help..

And after I changed the db to postgres, coursemology works fine with heroku: http://course-mology.heroku.com

**Comment by wilflare** [comment]
i've done gem update bundler
but I'm still getting the following error

Counting objects: 9858, done.

Delta compression using up to 4 threads.

Compressing objects: 100% (3108/3108), done.

Writing objects: 100% (9858/9858), 1.32 MiB | 360.00 KiB/s, done.

Total 9858 (delta 6289), reused 9858 (delta 6289)

remote: Compressing source files... done.

remote: Building source:

remote:

remote: -----> Ruby app detected

remote: -----> Compiling Ruby/Rails

remote: -----> Using Ruby version: ruby-2.0.0

remote: ###### WARNING:

remote:        Removing `Gemfile.lock` because it was generated on Windows.

remote:        Bundler will do a full resolve so native gems are handled
properly.

remote:        This may result in unexpected gem versions being used in
your app.

remote:        In rare occasions Bundler may not be able to resolve your
dependencies at all.

remote:        https://devcenter.heroku.com/articles/bundler-windows-gemfile

remote:

remote: -----> Installing dependencies using 1.9.7

remote:        Running: bundle install --without development:test --path
vendor/bundle --binstubs vendor/bundle/bin -j4

remote:        Fetching git://github.com/ledermann/unread.git

remote:        Fetching git://github.com/doabit/bootstrap-sass-extras.git

remote:        Fetching git://github.com/thedarkone/rails-dev-boost.git

remote:        Fetching git://github.com/lowjoel/acts_as_tenant.git

remote:        Fetching git://github.com/lowjoel/themes_on_rails.git

remote:        Fetching git://github.com/carrierwaveuploader/carrierwave.git

remote:        Fetching gem metadata from https://rails-assets.org/...

remote:        Fetching version metadata from https://rails-assets.org/..

remote:        Fetching gem metadata from https://rubygems.org/.......

remote:        Fetching version metadata from https://rubygems.org/...

remote:        Fetching dependency metadata from https://rubygems.org/..

remote:        Resolving dependencies...

remote:        Bundler could not find compatible versions for gem "bundler":

remote:        In Gemfile:

remote:        bundler (>= 1.10.3) ruby

remote:        Current Bundler version:

remote:        bundler (1.9.7)

remote:        This Gemfile requires a different version of Bundler.

remote:        Perhaps you need to update Bundler by running `gem install
bundler`?

remote:        Could not find gem 'bundler (>= 1.10.3) ruby in any of the
sources

remote:        Bundler Output: Fetching git://
github.com/ledermann/unread.git

remote:        Fetching git://github.com/doabit/bootstrap-sass-extras.git

remote:        Fetching git://github.com/thedarkone/rails-dev-boost.git

remote:        Fetching git://github.com/lowjoel/acts_as_tenant.git

remote:        Fetching git://github.com/lowjoel/themes_on_rails.git

remote:        Fetching git://github.com/carrierwaveuploader/carrierwave.git

remote:        Fetching gem metadata from https://rails-assets.org/...

remote:        Fetching version metadata from https://rails-assets.org/..

remote:        Fetching gem metadata from https://rubygems.org/.......

remote:        Fetching version metadata from https://rubygems.org/...

remote:        Fetching dependency metadata from https://rubygems.org/..

remote:        Resolving dependencies...

remote:        Bundler could not find compatible versions for gem "bundler":

remote:        In Gemfile:

remote:        bundler (>= 1.10.3) ruby

remote:

remote:        Current Bundler version:

remote:        bundler (1.9.7)

remote:        This Gemfile requires a different version of Bundler.

remote:        Perhaps you need to update Bundler by running `gem install
bundler`?

remote:        Could not find gem 'bundler (>= 1.10.3) ruby in any of the
sources

remote:  !

remote:  !     Failed to install gems via Bundler.

remote:  !

remote:

remote:  !     Push rejected, failed to compile Ruby app

remote:

remote: Verifying deploy....

remote:

remote: ! Push rejected to sleepy-atoll-2016.

remote:

To https://git.heroku.com/sleepy-atoll-2016.git

 ! [remote rejected] master -> master (pre-receive hook declined)

error: failed to push some refs to '
https://git.heroku.com/sleepy-atoll-2016.git'

wiLMBP:coursemology2 wilflare$

**Comment by allenwq** [comment]
Your bundler and ruby version are still not correct.

And coursemology2 is not ready for use yet, still under development.

**Comment by wilflare** [comment]
ah.. okie i'll stick with Coursemology1 then...
I know this may be too much to ask... but do you have a step-by-step guide
in deploying to Heroku?
(especially changing db to postgres

**Comment by allenwq** [comment]
OK, I can send you a guide later today. And let's contact through emails ? So that I will close this issue.

**Comment by wilflare** [comment]
sure email is fine! do you have mine?
so sorry to trouble you

**Comment by allenwq** [comment]
No problem. Sorry I don't have your email

**Comment by wilflare** [comment]
just emailed you at qwang@comp.nus.edu.sg
thank you so much!
